version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: securityrecap-db
    environment:
      POSTGRES_USER: securityrecap
      POSTGRES_PASSWORD: securityrecap
      POSTGRES_DB: securityrecap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
